# .github/workflows/main.yml

name: Trigger aboutme Netlify Build
on:
  schedule:
    # Run at 0815 daily
    - cron: '46 14 * * *'
jobs:
  build:
    name: Request aboutme_update Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e133796380a01bb8eb41958